ES\Bundle\BaseBundle\Model\ContactMessage:
    type: mappedSuperclass
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 255
        message:
            type: text
        createdAt:
            column: created_at
            type: datetime
            gedmo:
                timestampable:
                    on: create
