es_base_staging_login:
    pattern:  /staging/login
    defaults: { _controller: ESBaseBundle:StagingSecurity:login }
es_base_staging_login_check:
    pattern:  /staging/login_check
    defaults: { _controller: ESBaseBundle:StagingSecurity:loginCheck }
